# Site settings
title: fMRI data analysis and research at University of California, San Diego
lab_name: Leolabo
author: >
  Teo Imototar, Leela Noguchi and Leolabo
institution: UCSD
email: teoimototar@gmail.com
        leela.noguchi@gmail.com
description: >
  Leolabo performs neuroimaging data analysis
twitter_username: leolabo_
github_username:  leolabo
images_dir: "/images/"

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/

#plugins for search engine optimization
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap