# Site settings
title: Translational lymphoma research in the Leolabo at University of California, San Diego
lab_name: Leolabo
author: >
  Teo Imototar, Leela Noguchi and Leolabo
institution: UCSD
email: teoimototar@gmail.com
        leela.noguchi@gmail.com
description: >
  The Leolabo performs cutting-edge lymphoma research using
  a combination of dry lab and wet lab experiments.
twitter_username: leolabo_
github_username:  leolabo
images_dir: "/images/"

# Build settings
markdown: kramdown
include: ["_pages"]
permalink: /:title/

#plugins for search engine optimization
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap